#!/usr/bin/env php
<?php

// Register The Auto Loader
require __DIR__.'/bootstrap/autoload.php';

// This bootstraps the framework and gets it ready for use
$app = require_once __DIR__.'/bootstrap/app.php';

try {
    $app->execute();
} catch (Exception $e) {
    echo $e->getMessage().PHP_EOL;
    exit(255);
}
